version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/rest-api-portfolio main.go 

    run: 
        desc: Run the app
        cmds:
        - ./run.sh

    deploy: 
        desc: Deploy the app
        cmds:
        - flyctl deploy